apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: whataservice
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    inputDigest: {}
  local:
    useBuildkit: false
    concurrency: 1
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: qcon-workshop
        chartPath: chart
        recreatePods: false
        skipBuildDependencies: false
        artifactOverrides:
          components.whataservice.image: whataservice
        useHelmSecrets: false
        wait: false
